export interface ColombiaCity {
  ciudad: string;
  departamento: string;
}

// Solo ciudades principales de Colombia (no municipios pequeños)
export const COLOMBIA_CITIES: ColombiaCity[] = [
  // Bogotá D.C.
  { ciudad: "Bogotá", departamento: "Bogotá D.C." },
  // Antioquia
  { ciudad: "Medellín", departamento: "Antioquia" },
  { ciudad: "Bello", departamento: "Antioquia" },
  { ciudad: "Itagüí", departamento: "Antioquia" },
  { ciudad: "Envigado", departamento: "Antioquia" },
  { ciudad: "Sabaneta", departamento: "Antioquia" },
  { ciudad: "La Estrella", departamento: "Antioquia" },
  { ciudad: "Copacabana", departamento: "Antioquia" },
  { ciudad: "Girardota", departamento: "Antioquia" },
  { ciudad: "Barbosa", departamento: "Antioquia" },
  { ciudad: "Rionegro", departamento: "Antioquia" },
  { ciudad: "Apartadó", departamento: "Antioquia" },
  { ciudad: "Turbo", departamento: "Antioquia" },
  { ciudad: "Caucasia", departamento: "Antioquia" },
  { ciudad: "Yarumal", departamento: "Antioquia" },
  { ciudad: "Marinilla", departamento: "Antioquia" },
  { ciudad: "Santa Fe de Antioquia", departamento: "Antioquia" },
  { ciudad: "Puerto Berrío", departamento: "Antioquia" },
  { ciudad: "Caldas", departamento: "Antioquia" },
  { ciudad: "Andes", departamento: "Antioquia" },
  { ciudad: "Jericó", departamento: "Antioquia" },
  { ciudad: "Chigorodó", departamento: "Antioquia" },
  { ciudad: "Carepa", departamento: "Antioquia" },
  { ciudad: "Segovia", departamento: "Antioquia" },
  { ciudad: "El Bagre", departamento: "Antioquia" },
  // Atlántico
  { ciudad: "Barranquilla", departamento: "Atlántico" },
  { ciudad: "Soledad", departamento: "Atlántico" },
  { ciudad: "Malambo", departamento: "Atlántico" },
  { ciudad: "Sabanalarga", departamento: "Atlántico" },
  { ciudad: "Baranoa", departamento: "Atlántico" },
  { ciudad: "Galapa", departamento: "Atlántico" },
  { ciudad: "Puerto Colombia", departamento: "Atlántico" },
  // Bolívar
  { ciudad: "Cartagena", departamento: "Bolívar" },
  { ciudad: "Magangué", departamento: "Bolívar" },
  { ciudad: "Turbaco", departamento: "Bolívar" },
  { ciudad: "El Carmen de Bolívar", departamento: "Bolívar" },
  { ciudad: "Mompox", departamento: "Bolívar" },
  { ciudad: "Arjona", departamento: "Bolívar" },
  // Boyacá
  { ciudad: "Tunja", departamento: "Boyacá" },
  { ciudad: "Duitama", departamento: "Boyacá" },
  { ciudad: "Sogamoso", departamento: "Boyacá" },
  { ciudad: "Chiquinquirá", departamento: "Boyacá" },
  { ciudad: "Paipa", departamento: "Boyacá" },
  { ciudad: "Villa de Leyva", departamento: "Boyacá" },
  { ciudad: "Puerto Boyacá", departamento: "Boyacá" },
  // Caldas
  { ciudad: "Manizales", departamento: "Caldas" },
  { ciudad: "La Dorada", departamento: "Caldas" },
  { ciudad: "Riosucio", departamento: "Caldas" },
  { ciudad: "Villamaría", departamento: "Caldas" },
  { ciudad: "Chinchiná", departamento: "Caldas" },
  { ciudad: "Anserma", departamento: "Caldas" },
  { ciudad: "Salamina", departamento: "Caldas" },
  // Caquetá
  { ciudad: "Florencia", departamento: "Caquetá" },
  { ciudad: "San Vicente del Caguán", departamento: "Caquetá" },
  // Casanare
  { ciudad: "Yopal", departamento: "Casanare" },
  { ciudad: "Aguazul", departamento: "Casanare" },
  { ciudad: "Villanueva", departamento: "Casanare" },
  { ciudad: "Paz de Ariporo", departamento: "Casanare" },
  { ciudad: "Tauramena", departamento: "Casanare" },
  // Cauca
  { ciudad: "Popayán", departamento: "Cauca" },
  { ciudad: "Santander de Quilichao", departamento: "Cauca" },
  { ciudad: "Puerto Tejada", departamento: "Cauca" },
  { ciudad: "Patía", departamento: "Cauca" },
  { ciudad: "Guapi", departamento: "Cauca" },
  // Cesar
  { ciudad: "Valledupar", departamento: "Cesar" },
  { ciudad: "Aguachica", departamento: "Cesar" },
  { ciudad: "Agustín Codazzi", departamento: "Cesar" },
  { ciudad: "Bosconia", departamento: "Cesar" },
  { ciudad: "La Jagua de Ibirico", departamento: "Cesar" },
  { ciudad: "Curumaní", departamento: "Cesar" },
  // Chocó
  { ciudad: "Quibdó", departamento: "Chocó" },
  { ciudad: "Istmina", departamento: "Chocó" },
  { ciudad: "Bahía Solano", departamento: "Chocó" },
  { ciudad: "Nuquí", departamento: "Chocó" },
  // Córdoba
  { ciudad: "Montería", departamento: "Córdoba" },
  { ciudad: "Lorica", departamento: "Córdoba" },
  { ciudad: "Sahagún", departamento: "Córdoba" },
  { ciudad: "Cereté", departamento: "Córdoba" },
  { ciudad: "Montelíbano", departamento: "Córdoba" },
  { ciudad: "Planeta Rica", departamento: "Córdoba" },
  { ciudad: "Tierralta", departamento: "Córdoba" },
  // Cundinamarca
  { ciudad: "Soacha", departamento: "Cundinamarca" },
  { ciudad: "Facatativá", departamento: "Cundinamarca" },
  { ciudad: "Zipaquirá", departamento: "Cundinamarca" },
  { ciudad: "Chía", departamento: "Cundinamarca" },
  { ciudad: "Girardot", departamento: "Cundinamarca" },
  { ciudad: "Fusagasugá", departamento: "Cundinamarca" },
  { ciudad: "Mosquera", departamento: "Cundinamarca" },
  { ciudad: "Madrid", departamento: "Cundinamarca" },
  { ciudad: "Funza", departamento: "Cundinamarca" },
  { ciudad: "Cajicá", departamento: "Cundinamarca" },
  { ciudad: "La Mesa", departamento: "Cundinamarca" },
  { ciudad: "Tocancipá", departamento: "Cundinamarca" },
  { ciudad: "Sopó", departamento: "Cundinamarca" },
  { ciudad: "Tabio", departamento: "Cundinamarca" },
  { ciudad: "Cota", departamento: "Cundinamarca" },
  { ciudad: "Sibaté", departamento: "Cundinamarca" },
  { ciudad: "Villeta", departamento: "Cundinamarca" },
  { ciudad: "La Calera", departamento: "Cundinamarca" },
  // Guaviare
  { ciudad: "San José del Guaviare", departamento: "Guaviare" },
  // Huila
  { ciudad: "Neiva", departamento: "Huila" },
  { ciudad: "Pitalito", departamento: "Huila" },
  { ciudad: "Garzón", departamento: "Huila" },
  { ciudad: "La Plata", departamento: "Huila" },
  { ciudad: "Campoalegre", departamento: "Huila" },
  { ciudad: "San Agustín", departamento: "Huila" },
  // La Guajira
  { ciudad: "Riohacha", departamento: "La Guajira" },
  { ciudad: "Maicao", departamento: "La Guajira" },
  { ciudad: "Uribia", departamento: "La Guajira" },
  { ciudad: "Fonseca", departamento: "La Guajira" },
  // Magdalena
  { ciudad: "Santa Marta", departamento: "Magdalena" },
  { ciudad: "Ciénaga", departamento: "Magdalena" },
  { ciudad: "Fundación", departamento: "Magdalena" },
  { ciudad: "El Banco", departamento: "Magdalena" },
  { ciudad: "Aracataca", departamento: "Magdalena" },
  { ciudad: "Plato", departamento: "Magdalena" },
  // Meta
  { ciudad: "Villavicencio", departamento: "Meta" },
  { ciudad: "Acacías", departamento: "Meta" },
  { ciudad: "Granada", departamento: "Meta" },
  { ciudad: "Puerto López", departamento: "Meta" },
  { ciudad: "Puerto Gaitán", departamento: "Meta" },
  { ciudad: "La Macarena", departamento: "Meta" },
  // Nariño
  { ciudad: "Pasto", departamento: "Nariño" },
  { ciudad: "Tumaco", departamento: "Nariño" },
  { ciudad: "Ipiales", departamento: "Nariño" },
  { ciudad: "Túquerres", departamento: "Nariño" },
  { ciudad: "La Unión", departamento: "Nariño" },
  { ciudad: "Samaniego", departamento: "Nariño" },
  { ciudad: "Barbacoas", departamento: "Nariño" },
  // Norte de Santander
  { ciudad: "Cúcuta", departamento: "Norte de Santander" },
  { ciudad: "Ocaña", departamento: "Norte de Santander" },
  { ciudad: "Pamplona", departamento: "Norte de Santander" },
  { ciudad: "Villa del Rosario", departamento: "Norte de Santander" },
  { ciudad: "Los Patios", departamento: "Norte de Santander" },
  { ciudad: "Tibú", departamento: "Norte de Santander" },
  // Putumayo
  { ciudad: "Mocoa", departamento: "Putumayo" },
  { ciudad: "Puerto Asís", departamento: "Putumayo" },
  { ciudad: "Orito", departamento: "Putumayo" },
  { ciudad: "Valle de Guamuez", departamento: "Putumayo" },
  // Quindío
  { ciudad: "Armenia", departamento: "Quindío" },
  { ciudad: "Calarcá", departamento: "Quindío" },
  { ciudad: "Montenegro", departamento: "Quindío" },
  { ciudad: "Quimbaya", departamento: "Quindío" },
  { ciudad: "La Tebaida", departamento: "Quindío" },
  { ciudad: "Salento", departamento: "Quindío" },
  // Risaralda
  { ciudad: "Pereira", departamento: "Risaralda" },
  { ciudad: "Dosquebradas", departamento: "Risaralda" },
  { ciudad: "La Virginia", departamento: "Risaralda" },
  { ciudad: "Santa Rosa de Cabal", departamento: "Risaralda" },
  { ciudad: "Belén de Umbría", departamento: "Risaralda" },
  // San Andrés y Providencia
  { ciudad: "San Andrés", departamento: "San Andrés y Providencia" },
  { ciudad: "Providencia", departamento: "San Andrés y Providencia" },
  // Santander
  { ciudad: "Bucaramanga", departamento: "Santander" },
  { ciudad: "Floridablanca", departamento: "Santander" },
  { ciudad: "Girón", departamento: "Santander" },
  { ciudad: "Piedecuesta", departamento: "Santander" },
  { ciudad: "Barrancabermeja", departamento: "Santander" },
  { ciudad: "San Gil", departamento: "Santander" },
  { ciudad: "Socorro", departamento: "Santander" },
  { ciudad: "Málaga", departamento: "Santander" },
  { ciudad: "Vélez", departamento: "Santander" },
  { ciudad: "Lebrija", departamento: "Santander" },
  { ciudad: "Puerto Wilches", departamento: "Santander" },
  // Sucre
  { ciudad: "Sincelejo", departamento: "Sucre" },
  { ciudad: "Corozal", departamento: "Sucre" },
  { ciudad: "San Marcos", departamento: "Sucre" },
  { ciudad: "Sampués", departamento: "Sucre" },
  { ciudad: "Tolú", departamento: "Sucre" },
  { ciudad: "Coveñas", departamento: "Sucre" },
  // Tolima
  { ciudad: "Ibagué", departamento: "Tolima" },
  { ciudad: "Espinal", departamento: "Tolima" },
  { ciudad: "Melgar", departamento: "Tolima" },
  { ciudad: "Honda", departamento: "Tolima" },
  { ciudad: "Chaparral", departamento: "Tolima" },
  { ciudad: "Líbano", departamento: "Tolima" },
  { ciudad: "Mariquita", departamento: "Tolima" },
  { ciudad: "Purificación", departamento: "Tolima" },
  { ciudad: "Flandes", departamento: "Tolima" },
  // Valle del Cauca
  { ciudad: "Cali", departamento: "Valle del Cauca" },
  { ciudad: "Buenaventura", departamento: "Valle del Cauca" },
  { ciudad: "Palmira", departamento: "Valle del Cauca" },
  { ciudad: "Tuluá", departamento: "Valle del Cauca" },
  { ciudad: "Buga", departamento: "Valle del Cauca" },
  { ciudad: "Cartago", departamento: "Valle del Cauca" },
  { ciudad: "Yumbo", departamento: "Valle del Cauca" },
  { ciudad: "Jamundí", departamento: "Valle del Cauca" },
  { ciudad: "Florida", departamento: "Valle del Cauca" },
  { ciudad: "Zarzal", departamento: "Valle del Cauca" },
  { ciudad: "Roldanillo", departamento: "Valle del Cauca" },
  { ciudad: "Sevilla", departamento: "Valle del Cauca" },
  { ciudad: "Caicedonia", departamento: "Valle del Cauca" },
  { ciudad: "Candelaria", departamento: "Valle del Cauca" },
  { ciudad: "Pradera", departamento: "Valle del Cauca" },
  // Vaupés
  { ciudad: "Mitú", departamento: "Vaupés" },
  // Vichada
  { ciudad: "Puerto Carreño", departamento: "Vichada" },
  // Arauca
  { ciudad: "Arauca", departamento: "Arauca" },
  { ciudad: "Saravena", departamento: "Arauca" },
  { ciudad: "Arauquita", departamento: "Arauca" },
  // Amazonas
  { ciudad: "Leticia", departamento: "Amazonas" },
  // Guainía
  { ciudad: "Inírida", departamento: "Guainía" },
];
